// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giqvowkhdrgrplprsnpe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpcXZvd2toZHJncnBscHJzbnBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwODMxMjcsImV4cCI6MjA2ODY1OTEyN30.UqKCMkvCkPa6eh6nuqPnFolMBZHYJyAXt6go8aD_6Kw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});